apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - crossplane-core
  - crossplane-gcp-provider
#  - crossplane-composite-functions
#  - crossplane-helm-provider
#  - helm-providerconfig
#  - crossplane-kubernetes-provider
#  - kubernetes-providerconfig