apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - crossplane-core.yaml
  - crossplane-gcp-provider.yaml
  - gcp-providerconfig.yaml
  - composite-functions.yaml
  - crossplane-mongodbatlas-provider.yaml
  - mongodbatlas-providerconfig.yaml
#  - crossplane-confluent-provider.yaml
#  - confluent-providerconfig.yaml
#  - crossplane-kafka-provider.yaml
#  - vma-infra.yaml
#  - vma-apps.yaml
#  - crossplane-helm-provider.yaml
#  - helm-providerconfig.yaml
#  - crossplane-kubernetes-provider.yaml
#  - kubernetes-providerconfig.yaml
#  - compositions.yaml
