apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - crossplane-helmrelease.yaml
  - crossplane-provider-package.yaml
  - upbound-providerconfig.yaml
#  - crossplane-helm-provider.yaml
